variable "project_id" {}
variable "region" {}
variable "vpc_name" {}
variable "subnet_name" {}
variable "cluster_name" {}
variable "num_nodes" {}
variable "machine_type" {}
variable "node_label" {}
variable "max_pods_per_node" {}
