name: Deploy to GCP with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: halogen-obelisk-441705-u4  # Directly use your project ID here
          export_default_credentials: true

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Check for Existing Cluster
        id: check-cluster
        run: |
          CLUSTER_NAME="my-cluster"
          ZONE="us-central1-a"
          PROJECT="halogen-obelisk-441705-u4"
          if gcloud container clusters describe $CLUSTER_NAME --zone $ZONE --project $PROJECT; then
            echo "Cluster already exists." 
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "Cluster does not exist."
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Import Cluster to Terraform (if exists)
        if: env.exists == 'true'
        run: |
          terraform import google_container_cluster.primary projects/halogen-obelisk-441705-u4/locations/us-central1/clusters/my-cluster

      - name: Terraform Apply
        run: terraform apply -auto-approve
